-- Magic-link auth tokens generated by the Telegram bot /login command.
-- Each token is a one-time UUID valid for 15 minutes.
-- Accessed only via service_role (bot writes, web /api/bot-auth validates).

CREATE TABLE auth_tokens (
  token       UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  telegram_id BIGINT      NOT NULL,
  name        TEXT        NOT NULL,
  expires_at  TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '15 minutes'),
  used        BOOLEAN     NOT NULL DEFAULT FALSE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for fast token lookups on validation
CREATE INDEX idx_auth_tokens_token ON auth_tokens (token);

-- Optional: auto-cleanup old tokens (requires pg_cron or manual job)
-- For now, the web route checks expires_at in application logic.
